export const Municipios = [
    '9 de Julio',
    '25 de Mayo',
    'Angaco',
    'Albardon',
    'Calingasta',
    'Capital',
    'Caucete',
    'Chimbas',
    'Iglesia',
    'Jachal',
    'Pocito',
    'Ullum',
    'San Martin',
    'Santa Lucia',
    'Sarmiento',
    'Rawson',
    'Rivadavia',
    'Valle Fertil',
    'Zonda',
];
