export class IIntegrante {
    id: Number;
    encuestaId: String;
    apellido: String;
    nombre: String;
    tipoDocumento: String;
    numeroDocumento: String;
    esJefeHogar: Boolean;
    nacionalidad: String;
    sexo: String;
    genero: String;
    vinculoConJefeHogar: String;
    fechaNacimiento: Date;
    ocupacion: String;
    beneficioSocial: String;
    nivelEducativo: String;
    nivelEducativoIncompletoEstado: String;
    estadoCursada: String;
    enfermedadesCronicas: String;
    asistenciaAlimentaria: Boolean;
    embarazada: Boolean;
    esquemaVacunacion: Boolean;
    coberturaSalud: String;
    lugarAtencion: String;
    discapacidad: String;
    certificadoDiscapacidad: Boolean;
    cudNumero: String;
    cudVigencia: Date;
}
