export const CreateIntegranteQuery = `CREATE TABLE IF NOT EXISTS integrante(
    id INTEGER NOT NULL PRIMARY KEY,
    hogarId INTEGER,
    idUsuarioCreacion INTEGER,
    idUsuarioActualizacion  INTEGER,
    fechaCreacion DATETIME,
    fechaActualizacion DATETIME,
    esJefeHogar BOOLEAN,
    apellido VARCHAR(100),
    nombre VARCHAR(100),
    tipoDocumento VARCHAR(100),
    numeroDocumento VARCHAR(100),
    nacionalidad VARCHAR(100),
    sexo VARCHAR(100),
    genero VARCHAR(100),
    etnia VARCHAR(100),
    vinculoConJefeHogar VARCHAR(100),
    fechaNacimiento DATETIME,
    ocupacion VARCHAR(100),
    beneficioSocial VARCHAR(100),
    nivelEducativo VARCHAR(100),
    nivelEducativoEstado VARCHAR(100),
    asistenciaAlimentaria BOOLEAN,
    embarazada BOOLEAN,
    embarzadaEstado VARCHAR(100),
    antitetanica BOOLEAN,
    esquemaVacunacion BOOLEAN,
    coberturaSalud VARCHAR(100),
    lugarAtencion VARCHAR(100),
    lugarAtencionOtro VARCHAR(100),
    discapacidad VARCHAR(100),
    certificadoDiscapacidad VARCHAR(100),
    cudNumero VARCHAR(100),
    cudVigencia DATETIME
    )`;

export const InsertIntegranteQuery = `INSERT INTO integrante(
    hogarId,
    idUsuarioCreacion,
    idUsuarioActualizacion,
    fechaCreacion,
    fechaActualizacion,
    esJefeHogar,
    apellido,
    nombre,
    tipoDocumento,
    numeroDocumento,
    nacionalidad,
    sexo,
    genero,
    etnia,
    vinculoConJefeHogar,
    fechaNacimiento,
    ocupacion,
    beneficioSocial,
    nivelEducativo,
    nivelEducativoEstado,
    asistenciaAlimentaria,
    embarazada,
    embarzadaEstado,
    antitetanica,
    esquemaVacunacion,
    coberturaSalud,
    lugarAtencion,
    lugarAtencionOtro,
    discapacidad,
    certificadoDiscapacidad,
    cudNumero,
    cudVigencia
)
VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`;

export const UpdateIntegranteQuery = `UPDATE integrante SET
    hogarId=?,
    idUsuarioCreacion=?,
    idUsuarioActualizacion=?,
    fechaCreacion=?,
    fechaActualizacion=?,
    esJefeHogar=?,
    apellido=?,
    nombre=?,
    tipoDocumento=?,
    numeroDocumento=?,
    nacionalidad=?,
    sexo=?,
    genero=?,
    etnia=?,
    vinculoConJefeHogar=?,
    fechaNacimiento=?,
    ocupacion=?,
    beneficioSocial=?,
    nivelEducativo=?,
    nivelEducativoEstado=?,
    asistenciaAlimentaria=?,
    embarazada=?,
    embarzadaEstado=?,
    antitetanica=?,
    esquemaVacunacion=?,
    coberturaSalud=?,
    lugarAtencion=?,
    lugarAtencionOtro=?,
    discapacidad=?,
    certificadoDiscapacidad=?,
    cudNumero=?,
    cudVigencia=?
    WHERE id =?`;

export const SelectHogarQuery = `SELECT i.* FROM integrante i
    WHERE h.id = `;

export const SelectIntegrantesByHogarQuery = `SELECT * FROM integrante
    WHERE hogarId = `;

