export const CreateViviendaQuery = `CREATE TABLE IF NOT EXISTS vivienda(
    id INTEGER NOT NULL PRIMARY KEY,
    parcelaId INTEGER,
    idUsuarioCreacion INTEGER,
    idUsuarioActualizacion INTEGER,
    fechaCreacion DATETIME,
    fechaActualizacion DATETIME,
    materialPiso VARCHAR(100),
    materialPared VARCHAR(100),
    materialTecho VARCHAR(100),
    cantidadHabitacionesSinServicio VARCHAR(100),
    tipoCasa VARCHAR(100),
    fuenteAgua VARCHAR(100),
    tipoBano VARCHAR(100),
    tieneInstalacionesElectricas VARCHAR(100),
    tieneTratamientoBasura BOOLEAN,
    tieneAnimalesConsumo BOOLEAN,
    animalesConsumoVacunados BOOLEAN,
    animalesConsumoDesparasitados BOOLEAN,
    tieneAnimalesDomesticos BOOLEAN,
    animalesDomesticosVacunados BOOLEAN,
    animalesDomesticosDesparasitados BOOLEAN,
    internet BOOLEAN,
    tvCable BOOLEAN,
    dtv BOOLEAN,
    automovil BOOLEAN,
    moto BOOLEAN,
    lineaTelefono BOOLEAN,
    celularSinInternet BOOLEAN,
    celularConInternet BOOLEAN,
    otrosDatos VARCHAR(100)
    )`;

export const InsertViviendaQuery = `INSERT INTO vivienda(
    parcelaId,
    idUsuarioCreacion,
    idUsuarioActualizacion,
    fechaCreacion,
    fechaActualizacion,
    materialPiso,
    materialPared,
    materialTecho,
    cantidadHabitacionesSinServicio,
    tipoCasa,
    fuenteAgua,
    tipoBano,
    tieneInstalacionesElectricas,
    tieneTratamientoBasura,
    tieneAnimalesConsumo,
    animalesConsumoVacunados,
    animalesConsumoDesparasitados,
    tieneAnimalesDomesticos,
    animalesDomesticosVacunados,
    animalesDomesticosDesparasitados,
    internet,
    tvCable,
    dtv,
    automovil,
    moto,
    lineaTelefono,
    celularSinInternet,
    celularConInternet,
    otrosDatos )
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`;

export const UpdateViviendaQuery = `UPDATE vivienda SET
    parcelaId=?,
    idUsuarioCreacion=?,
    idUsuarioActualizacion=?,
    fechaCreacion=?,
    fechaActualizacion=?,
    materialPiso=?,
    materialPared=?,
    materialTecho=?,
    cantidadHabitacionesSinServicio=?,
    tipoCasa=?,
    fuenteAgua=?,
    tipoBano=?,
    tieneInstalacionesElectricas=?,
    tieneTratamientoBasura=?,
    tieneAnimalesConsumo=?,
    animalesConsumoVacunados=?,
    animalesConsumoDesparasitados=?,
    tieneAnimalesDomesticos=?,
    animalesDomesticosVacunados=?,
    animalesDomesticosDesparasitados=?,
    internet=?,
    tvCable=?,
    dtv=?,
    automovil=?,
    moto=?,
    lineaTelefono=?,
    celularSinInternet=?,
    celularConInternet=?,
    otrosDatos=?
    WHERE id=?`;

export const SelectViviendaQuery = `SELECT v.* FROM vivienda v
WHERE v.id = `;

export const SelectViviendaByParcelaQuery = `SELECT * FROM vivienda
WHERE parcelaId = `;

